spring.application.name=campus-pulse
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/campus-pulse}
campus-pulse.demo-data=true
spring.thymeleaf.cache=false
server.port=${PORT:8080}